version: '3'
services:
    devenv:
        build:
            context: ./
            dockerfile: Dockerfile
        image: devenv/base
        container_name: devenv
        volumes:
            - ../../Workspace:/Workspace
            - ../../Programs:/Programs
            - /tmp/.X11-unix:/tmp/.X11-unix:rw
            - /etc/group:/etc/group:ro
            - /etc/passwd:/etc/passwd:ro
            - /etc/shadow:/etc/shadow:ro
            - /etc/sudoers.d:/etc/sudoers.d:ro
        environment:
            - DISPLAY=unix:0
        devices:
            - /dev/snd
        network_mode: host
        ports:
            - "6000:6000"
